name: Python Linter

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install linter
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Lint Python code
      run: |
        # Lint all Python files except migrations
        flake8 . --exclude=migrations --count --show-source --statistics